_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/yolox_cspdarknet.yml',
  './_base_/optimizer_300e.yml',
  './_base_/yolox_reader.yml',
]
pretrain_weights: https://paddledet.bj.bcebos.com/models/mot/yolox/torch2paddle_final_yolox/yolox_x_coco_paddle.pdparams

snapshot_epoch: 5
weights: output/yolox_x_mot/model_final

depth_factor: 1.33
width_factor: 1.25

metric: COCO
num_classes: 1

##### model
YOLOXHead:
  strides: [8, 16, 32]
  channels: [256, 512, 1024]
  depthwise: False
  mosaic_epoch: 70
  yolox_loss: YOLOXLoss

YOLOXLoss:
  loss_type: "iou"

YOLOXPostProcess:
  decode:
    name: YOLOXBox
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.001
    nms_threshold: 0.7


##### optimizer
epoch: 80
LearningRate:
  base_lr: 0.01
  schedulers:
  - !YOLOXCosineDecay
    max_epochs: 80
    no_aug_epochs: 10
    min_lr_ratio: 0.05
  - !ExpWarmup
    start_lr: 0.
    warmup_epochs: 1

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
    use_nesterov: true
    param_groups:
      - params: ['bias', 'bn']
        weight_decay: 0.
  regularizer:
    factor: 0.0005
    type: L2

##### reader: bytetrack use legacy YOLOX
worker_num: 4
TrainReader:
  inputs_def:
    num_max_boxes: 120
  sample_transforms:
    - Decode: {}
    - YOLOXMosaic: {prob: 1.0, input_dim: [800, 1440], enable_mixup: True}
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
    - RandomDistort: {}
    - RandomFlip: {}
    - BboxXYXY2XYWH: {} # [18,32]*32, [int(18*1.8), int(32*1.8)]*32
    #- RandomResize: {target_size: [[576, 1024], [608, 1088], [640, 1152], [672, 1216], [704, 1280], [736, 1344], [768, 1376], [800, 1440], [832, 1504], [864, 1568], [896, 1600], [928, 1664], [960, 1728], [992, 1792], [1024, 1856]], interp: 2, keep_ratio: True}
    #- RandomResize: {target_size: [[576, 1024], [608, 1088]], interp: 2, keep_ratio: True}
  batch_transforms:
    - BatchRandomResize: {target_size: [608, 640, 672, 704, 736, 768, 800], random_size: True, random_interp: True, keep_ratio: True}
    - YOLOXPadBox: {num_max_boxes: 120, init_bbox: [-9999.0, -9999.0, 10.0, 10.0]}
    - SquareImage: {fill_value: 114, is_channel_first: false}
    - Permute: {}
  batch_size: 8
  shuffle: true
  drop_last: true
  mosaic_epoch: 70 #
  mosaic_sample_num: 5
  use_shared_memory: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [1440, 1440], keep_ratio: True, interp: 1}
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  batch_transforms:
    - SquareImage: {fill_value: 114, is_channel_first: false}
    - Permute: {}
  batch_size: 1

TestReader:
  inputs_def:
    image_shape: [3, 800, 800]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [800, 800], keep_ratio: True, interp: 1}
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
    - SquareImage: {fill_value: 114, is_channel_first: false}
    - Permute: {}
  batch_size: 1


###### data
TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/train_half.json
    dataset_dir: dataset/MOT
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/val_half.json
    dataset_dir: dataset/MOT

TestDataset:
  !ImageFolder
    anno_path: annotations/val_half.json
