_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/yolox_cspdarknet.yml',
  './_base_/optimizer_300e.yml',
  './_base_/yolox_reader.yml',
]
snapshot_epoch: 10
find_unused_parameters: True
weights: output/yolox_s_coco_debug/model_final
depth_factor: 0.33
width_factor: 0.50

#################  for debug  #################
log_iter: 1

TrainDataset:
  !COCODataSet
    image_dir: val2017
    #anno_path: annotations/instances_val2017.json
    #anno_path: annotations/instances_val2017_im1.json
    anno_path: annotations/instances_val2017_im2.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    #anno_path: annotations/instances_val2017.json
    anno_path: annotations/instances_val2017_im8.json
    dataset_dir: dataset/coco

input_height: &input_height 640
input_width: &input_width 640
input_size: &input_size [*input_height, *input_width]

worker_num: 0 # 4
TrainReader:
  inputs_def:
    num_max_boxes: 120
  sample_transforms:
    - DecodeResize:
        target_size: *input_size
        keep_ratio: True
    #- Decode: {}
    #- RGBReverse: {}
    #- Resize: {target_size: *input_size, keep_ratio: True} # INTER_LINEAR
    - YOLOXMosaic:
        prob: 0.0 # 1.0
        degrees: 10.0
        translate: 0.1
        scale: [0.1, 2]
        shear: 2.0
        perspective: 0.0
        input_dim: *input_size
        enable_mixup: True
        mixup_prob: 1.0
        mixup_scale: [0.5, 1.5]
    - PadResize:
        target_size: *input_size
        fill_value: 114
        hsv_prob: 0.0 #1.0
        flip_prob: 0 #0.5
  batch_transforms:
    - RecBatchRandomResize:
        input_size: *input_size
        multiscale_range: 5
    - PadBox: {num_max_boxes: 120}
    - Permute: {}
  batch_size: 2 #1
  shuffle: False #True
  drop_last: True
  collate_batch: True 
  use_shared_memory: True
  mosaic_epoch: 1
  mosaic_sample_num: 5

EvalReader:
  sample_transforms:
    - Decode: {}
    - RGBReverse: {}
    - Resize: {target_size: *input_size, keep_ratio: True} # INTER_LINEAR
    - PadResize:
        target_size: *input_size
        fill_value: 114
  batch_transforms:
    - Permute: {}
  batch_size: 1

EvalReader2:
  sample_transforms:
    - DecodeResize:
        target_size: *input_size
        keep_ratio: True
    - PadResize:
        target_size: *input_size
        fill_value: 114
  batch_transforms:
    - Permute: {}
  batch_size: 1

TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - RGBReverse: {}
    - Resize: {target_size: *input_size, keep_ratio: True} # INTER_LINEAR
    - PadResize:
        target_size: *input_size
        fill_value: 114
  batch_transforms:
    - Permute: {}
  batch_size: 1

epoch: 1
LearningRate:
  base_lr: 0.2 #0.01 #0.000625
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [10]
    use_warmup: False

OptimizerBuilder: # no use
  optimizer:
    momentum: 0.9
    type: Momentum
    use_nesterov: true
  regularizer: # no use
    None
  #  factor: 0.0005
  #  type: L2



################################ old ################################
EvalReader0:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: True, interp: 1}
  batch_transforms:
    - SquareImage: {fill_value: 114, is_channel_first: false}
    - Permute: {}
  batch_size: 1

TestReader0:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: True, interp: 1}
    - SquareImage: {fill_value: 114, is_channel_first: false}
    - Permute: {}
  batch_size: 1

################################ old ################################
#epoch: 3
LearningRate0:
  base_lr: 0.000625
  schedulers:
  - !YOLOXCosineDecay
    max_epochs: 3
    no_aug_epochs: 3
    min_lr_ratio: 0.05
  - !ExpWarmup
    start_lr: 0.
    warmup_epochs: 3

OptimizerBuilder0:
  optimizer:
    momentum: 0.9
    type: Momentum
    use_nesterov: true
    param_groups:
      - params: ['bias', 'bn']
        weight_decay: 0.
  regularizer:
    None
    #factor: 0.0005
    #type: L2
################################ old ################################


######################## model 
architecture: YOLOX
YOLOX:
  backbone: CSPDarkNet
  neck: YOLOCSPPAN
  yolox_head: YOLOXHead
  post_process: YOLOXPostProcess2 ###

YOLOXHead:
  strides: [8, 16, 32]
  channels: [256, 512, 1024]
  depthwise: False
  mosaic_epoch: 1
  yolox_loss: YOLOXLoss

YOLOXPostProcess2: # slow but more accurate
  decode:
    name: YOLOXBox # no use
  nms:
    name: MultiClassNMS
    nms_top_k: 30000
    keep_top_k: 1000
    score_threshold: 0.001
    nms_threshold: 0.65
    return_index: true

YOLOXPostProcess:
  decode:
    name: YOLOXBox
  nms:
    name: MultiClassNMS
    nms_top_k: 30000
    keep_top_k: 1000
    score_threshold: 0.001
    nms_threshold: 0.65
    return_index: true