_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/yolox_cspdarknet.yml',
  './_base_/optimizer_3x.yml',
  './_base_/yolox_reader_416.yml',
]
log_iter: 50
snapshot_epoch: 2
weights: output/yolox_tiny_coco_3x/model_final
depth_factor: 0.33
width_factor: 0.375

use_ema: True

input_height: &input_height 416
input_width: &input_width 416
input_size: &input_size [*input_height, *input_width]
mosaic_epoch: &mosaic_epoch 34 #285

YOLOXHead:
  strides: [8, 16, 32]
  channels: [256, 512, 1024]
  depthwise: False
  mosaic_epoch: 33 #*mosaic_epoch
  yolox_loss: YOLOXLoss

YOLOXPostProcess:
  decode:
    name: YOLOXBox
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.01
    nms_threshold: 0.6
  
    #name: MultiClassNMS
    #nms_top_k: 30000
    #keep_top_k: 1000
    #score_threshold: 0.001
    #nms_threshold: 0.65

worker_num: 4
TrainReader:
  inputs_def:
    num_max_boxes: 120
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *input_size, keep_ratio: True}
    - YOLOXMosaic:
        prob: 1.0 # 0.5 in nano
        degrees: 10.0
        translate: 0.1
        scale: [0.5, 1.5] # [0.1, 2] in s/m/l/x
        shear: 2.0
        input_dim: *input_size
        enable_mixup: False # True in s/m/l/x
        mixup_prob: 1.0
        mixup_scale: [0.5, 1.5]
    - AugImage:
        target_size: *input_size
        hsv_prob: 1.0
        flip_prob: 0.5
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640], random_size: True, random_interp: True, keep_ratio: True}
    #- RecBatchRandomResize: {input_size: *input_size, nn_resize: True, keep_ratio: True, random_size_factor: [10, 20]}
    - PadBox: {num_max_boxes: 120}
    - Permute: {}
  batch_size: 8
  shuffle: True
  drop_last: True
  collate_batch: True 
  use_shared_memory: True
  mosaic_epoch: *mosaic_epoch
  mosaic_sample_num: 5
