_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/yolox_cspdarknet.yml',
  './_base_/optimizer_300e.yml',
  './_base_/yolox_reader.yml',
]
snapshot_epoch: 10
weights: output/yolox_s_coco/model_final
depth_factor: 0.33
width_factor: 0.50

#################  for debug  #################
log_iter: 1

TrainDataset:
  !COCODataSet
    image_dir: val2017
    #anno_path: annotations/instances_val2017.json
    anno_path: annotations/instances_val2017_im4.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    #anno_path: annotations/instances_val2017.json
    anno_path: annotations/instances_val2017_im8.json
    dataset_dir: dataset/coco

worker_num: 0
TrainReader:
  inputs_def:
    num_max_boxes: 120
  sample_transforms:
    - Decode: {}
    - RandomResize: {target_size: [640, 640], interp: 1, keep_ratio: True, random_size: False}
    #- Resize: {target_size: [640, 640], keep_ratio: True, interp: 1}
    #- YOLOXMosaic: {prob: 1.0, degrees: 10.0, translate: 0.1, scale: [0.1, 2], shear: 2.0, perspective: 0.0, input_dim: [640, 640]}
    #- RandomDistort: {}
    #- RandomFlip: {}
  batch_transforms:
    - BboxXYXY2XYWH: {}
    #- BatchRandomResize: {target_size: [448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832], random_size: True, random_interp: True, keep_ratio: True}
    - YOLOXPadBox: {num_max_boxes: 120, init_bbox: [-9999.0, -9999.0, 10.0, 10.0]}
    - SquareImage: {fill_value: 114, is_channel_first: false}
    - Permute: {}
  batch_size: 4
  shuffle: False #true
  drop_last: true
  mosaic_epoch: -1
  mosaic_sample_num: 5
  use_shared_memory: true


EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: True, interp: 1}
  batch_transforms:
    - SquareImage: {fill_value: 114, is_channel_first: false}
    - Permute: {}
  batch_size: 8


TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: True, interp: 1}
    - SquareImage: {fill_value: 114, is_channel_first: false}
    - Permute: {}
  batch_size: 1


epoch: 10
LearningRate:
  base_lr: 0.000625 #float(0.01 / 64.0 * 4) # 0.01
  schedulers:
  - !YOLOXCosineDecay
    max_epochs: 10
    no_aug_epochs: 3
    min_lr_ratio: 0.05
  - !ExpWarmup
    start_lr: 0.
    warmup_epochs: 3

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
    use_nesterov: true
    param_groups:
      - params: ['bias', 'bn']
        weight_decay: 0.
      #- params: ['weight']
      #  weight_decay: 0.0005
  regularizer:
    factor: 0.0005
    type: L2

######################## model 
architecture: YOLOX
use_ema: true
ema_decay: 0.9998
depth_factor: 0.33
width_factor: 0.50
act: silu

YOLOX:
  backbone: CSPDarkNet
  neck: YOLOPAFPN
  yolox_head: YOLOXHead
  post_process: YOLOXPostProcess

CSPDarkNet:
  arch: "X"
  return_idx: [2, 3, 4]
  #freeze_at: -1

YOLOPAFPN:
  channels: [256, 512, 1024]
  depthwise: False

YOLOXHead:
  strides: [8, 16, 32]
  channels: [256, 512, 1024]
  depthwise: False
  #mosaic_epoch: 285
  yolox_loss: YOLOXLoss

YOLOXLoss:
  loss_type: "iou"

YOLOXPostProcess:
  decode:
    name: YOLOXBox
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.001
    nms_threshold: 0.65
