_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/yolox_cspdarknet.yml',
  './_base_/optimizer_300e.yml',
  './_base_/yolox_reader.yml',
]

snapshot_epoch: 1
weights: output/yolox_s_coco/model_final

depth_factor: 0.33
width_factor: 0.50

TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017_im8.json
    dataset_dir: dataset/coco

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json


input_height: &input_height 640
input_width: &input_width 640
input_size: &input_size [*input_height, *input_width]

worker_num: 4
TrainReader:
  inputs_def:
    num_max_boxes: 120
  sample_transforms:
    - DecodeResize:
        target_size: *input_size
        keep_ratio: True
    - YOLOXMosaic:
        prob: 1.0
        degrees: 10.0
        translate: 0.1
        scale: [0.1, 2]
        shear: 2.0
        perspective: 0.0
        input_dim: *input_size
        enable_mixup: False #True
        mixup_prob: 1.0
        mixup_scale: [0.5, 1.5]
    - PadResize:
        target_size: *input_size
        fill_value: 114
        hsv_prob: 0.0 #
        flip_prob: 0.5
  batch_transforms:
    - RecBatchRandomResize:
        input_size: *input_size
        multiscale_range: 5
    - PadBox: {num_max_boxes: 120}
    - Permute: {}
  batch_size: 8
  shuffle: True
  drop_last: True
  collate_batch: True 
  use_shared_memory: True
  mosaic_epoch: 140
  mosaic_sample_num: 5

EvalReader:
  sample_transforms:
    - DecodeResize:
        target_size: *input_size
        keep_ratio: True
    - PadResize:
        target_size: *input_size
        fill_value: 114
  batch_transforms:
    - Permute: {}
  batch_size: 1


TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - DecodeResize:
        target_size: *input_size
        keep_ratio: True
    - PadResize:
        target_size: *input_size
        fill_value: 114
  batch_transforms:
    - Permute: {}
  batch_size: 1


epoch: 150

LearningRate:
  base_lr: 0.01
  schedulers:
  - !YOLOXCosineDecay
    max_epochs: 150
    no_aug_epochs: 10
    min_lr_ratio: 0.05
  - !ExpWarmup
    start_lr: 0.
    warmup_epochs: 3

OptimizerBuilder: # but no use, rewrite in trainer.py
  optimizer:
    momentum: 0.9
    type: Momentum
    use_nesterov: true
    #param_groups:
    #  - params: ['bias', 'bn']
    #    weight_decay: 0.
  regularizer:
    factor: 0.0005
    type: L2
