_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/yolox_cspdarknet.yml',
  './_base_/optimizer_300e.yml',
  './_base_/yolox_reader.yml',
]

snapshot_epoch: 5
weights: output/yolox_x_mot/model_final

depth_factor: 1.33
width_factor: 1.25

metric: COCO
num_classes: 1

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/train_half.json
    dataset_dir: dataset/mot/MOT17/images
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/val_half.json
    dataset_dir: dataset/mot/MOT17/images

TestDataset:
  !ImageFolder
    anno_path: annotations/val_half.json
