_BASE_: [
  'ppyoloe_crn_l_80e_visdrone.yml',
]
weights: output/ppyoloe_p2_crn_l_80e_visdrone/model_final

pretrain_weights: https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_300e_coco.pdparams

TrainReader:
  batch_size: 4

LearningRate:
  base_lr: 0.005

CSPResNet:
  return_idx: [0, 1, 2, 3]

CustomCSPPAN:
  out_channels: [768, 384, 192, 64]

PPYOLOEHead:
  static_assigner_epoch: -1
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.01
    nms_threshold: 0.6

PPYOLOEHead:
  fpn_strides: [4] #[32, 16, 8]
