epoch: 300

LearningRate:
  base_lr: 0.01
  schedulers:
  - !YOLOXCosineDecay
    max_epochs: 300
    no_aug_epochs: 15
    min_lr_ratio: 0.05
  - !ExpWarmup
    start_lr: 0.
    warmup_epochs: 5

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
    use_nesterov: true
    param_groups:
      - params: ['bias', 'bn']
        weight_decay: 0.
  regularizer:
    factor: 0.0005
    type: L2
