architecture: YOLOX
use_ema: True
ema_decay: 0.9999
ema_decay_type: "exponential"
depth_factor: 0.33
width_factor: 0.50
act: silu
find_unused_parameters: True
depth_mult: 0.33
width_mult: 0.50
norm_type: sync_bn

YOLOX:
  backbone: CSPResNet
  neck: YOLOCSPPAN
  yolox_head: YOLOXHead
  post_process: YOLOXPostProcess

CSPResNet:
  layers: [3, 6, 6, 3]
  channels: [64, 128, 256, 512, 1024]
  return_idx: [1, 2, 3]
  use_large_stem: True

CSPDarkNet:
  arch: "X"
  return_idx: [2, 3, 4]

YOLOCSPPAN:
  depthwise: False

YOLOXHead:
  strides: [8, 16, 32]
  channels: [256, 512, 1024]
  depthwise: False
  mosaic_epoch: 300
  yolox_loss: YOLOXLoss

YOLOXLoss:
  loss_type: "iou"

YOLOXPostProcess:
  decode:
    name: YOLOXBox
  nms:
    name: MultiClassNMS
    nms_top_k: 30000
    keep_top_k: 1000
    score_threshold: 0.001
    nms_threshold: 0.65
    return_index: true
