architecture: YOLOX
use_ema: True
ema_decay: 0.9999 # not 0.9998
depth_factor: 0.33
width_factor: 0.50
act: silu

YOLOX:
  backbone: CSPDarkNet
  neck: YOLOCSPPAN
  yolox_head: YOLOXHead
  post_process: YOLOXPostProcess

CSPDarkNet:
  arch: "X"
  return_idx: [2, 3, 4]

YOLOCSPPAN:
  depthwise: False

YOLOXHead:
  strides: [8, 16, 32]
  channels: [256, 512, 1024]
  depthwise: False
  mosaic_epoch: 285
  yolox_loss: YOLOXLoss

YOLOXLoss:
  loss_type: "iou"

YOLOXPostProcess:
  decode:
    name: YOLOXBox
  nms:
    name: MultiClassNMS
    nms_top_k: 30000
    keep_top_k: 1000
    score_threshold: 0.001
    nms_threshold: 0.65
    return_index: true
