worker_num: 4
TrainReader:
  inputs_def:
    num_max_boxes: 120
  sample_transforms:
    - DecodeResize: {target_size: [640, 640], keep_ratio: True, hsv_prob: 1.0, flip_prob: 0.5, fill_value: 114}
    - YOLOXMosaic: {prob: 1.0, degrees: 10.0, translate: 0.1, scale: [0.1, 2], shear: 2.0, perspective: 0.0, input_dim: [640, 640]}
  batch_transforms:
    - RecBatchRandomResize: {input_size: [640, 640], multiscale_range: 5}
    - PadBox: {num_max_boxes: 120}
    - Permute: {}
  batch_size: 4
  shuffle: True
  drop_last: True
  collate_batch: True 
  mosaic_epoch: 285
  mosaic_sample_num: 5
  use_shared_memory: True


EvalReader:
  sample_transforms:
    - DecodeResize: {target_size: [640, 640], keep_ratio: True, fill_value: 114}
  batch_transforms:
    - Permute: {}
  batch_size: 1


TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: True, interp: 1}
    - SquareImage: {fill_value: 114, is_channel_first: False}
    - Permute: {}
  batch_size: 1
