input_height: &input_height 640
input_width: &input_width 640
input_size: &input_size [*input_height, *input_width]
mosaic_epoch: &mosaic_epoch 285

worker_num: 4
TrainReader:
  inputs_def:
    num_max_boxes: 120
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *input_size, keep_ratio: True}
    - YOLOXMosaic:
        prob: 1.0
        degrees: 10.0
        translate: 0.1
        scale: [0.1, 2]
        shear: 2.0
        input_dim: *input_size
        enable_mixup: True
        mixup_prob: 1.0
        mixup_scale: [0.5, 1.5]
    - AugImage:
        target_size: *input_size
        hsv_prob: 1.0
        flip_prob: 0.5
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640], random_size: True, random_interp: True, keep_ratio: True}
    #- RecBatchRandomResize:
    #    input_size: *input_size
    #    nn_resize: True # only get target_size. resize in architecture
    #    keep_ratio: True # only for square
    #    multiscale_range: 5 # 480*480, 800*800
    - PadBox: {num_max_boxes: 120}
    - Permute: {}
  batch_size: 8
  shuffle: True
  drop_last: True
  collate_batch: True 
  use_shared_memory: True
  mosaic_epoch: *mosaic_epoch
  mosaic_sample_num: 5


EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *input_size, keep_ratio: True}
    - PadImage: {target_size: *input_size, fill_value: 114}
    - Permute: {}
  batch_size: 8


TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *input_size, keep_ratio: True}
    - PadImage: {target_size: *input_size, fill_value: 114}
    - Permute: {}
  batch_size: 1
