_BASE_: [
  './yolox_cspdarknet.yml',
]

YOLOX:
  backbone: ConvNeXt
  neck: YOLOCSPPAN
  head: YOLOXHead
  size_stride: 32
  size_range: [15, 25] # multi-scale range [480*480 ~ 800*800]


ConvNeXt:
  depths: [3, 3, 9, 3]
  dims: [96, 192, 384, 768]
  return_idx: [1, 2, 3]
  drop_path_rate: 0.4
  layer_scale_init_value: 1.0
  pretrained: https://paddledet.bj.bcebos.com/models/pretrained/convnext_tiny_1k_224_ema.pdparams
