architecture: YOLOv3
use_ema: true
ema_decay: 0.9998
act: silu
fuse_model: False # TODO

depth_factor: 0.33
width_factor: 0.50

YOLOv3:
  backbone: CSPDarkNet
  neck: YOLOPAFPN
  yolo_head: YOLOv3Head
  post_process: YOLOv5PostProcess

CSPDarkNet:
  arch: "P5"
  return_idx: [2, 3, 4]

YOLOPAFPN:
  channels: [256, 512, 1024]
  depthwise: false

YOLOv3Head:
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  loss: YOLOv5Loss

YOLOv5Loss:
  downsample: [32, 16, 8]
  label_smooth: false

YOLOv5PostProcess:
  decode:
    name: YOLOv5Box
    conf_thresh: 0.001
    downsample_ratio: 32
  nms:
    name: MultiClassNMS
    keep_top_k: 1000
    score_threshold: 0.001
    nms_threshold: 0.65
    nms_top_k: 30000
    return_index: true
