architecture: YOLOv3
use_ema: true
ema_decay: 0.9998
act: silu
fuse_model: False # TODO

depth_factor: 0.33
width_factor: 0.50

YOLOv3:
  backbone: CSPDarkNet
  neck: YOLOCSPPAN
  yolo_head: YOLOv3Head
  post_process: YOLOv5PostProcess

CSPDarkNet:
  arch: "P6"
  return_idx: [2, 3, 4, 5]

YOLOCSPPAN:
  depthwise: false

YOLOv3Head:
  anchors: [[19, 27], [44, 40], [38, 94],
            [96, 68], [86, 152], [180, 137],
            [140, 301], [303, 264], [238, 542],
            [436, 615], [739, 380], [925, 792]]
  anchor_masks: [[9, 10, 11], [6, 7, 8], [3, 4, 5], [0, 1, 2]]
  loss: YOLOv5Loss

YOLOv5Loss:
  balance: [4.0, 1.0, 0.4]
  box_weight: 0.05
  obj_weight: 1.0
  cls_weght: 0.5

YOLOv5PostProcess:
  decode:
    name: YOLOv5Box
    conf_thresh: 0.001
    downsample_ratio: 64 # 32
  nms:
    name: MultiClassNMS
    keep_top_k: 1000
    score_threshold: 0.001
    nms_threshold: 0.65
    nms_top_k: 30000
    return_index: true
