_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_270e.yml',
  '_base_/yolov3_darknet53.yml',
  '_base_/yolov3_reader.yml',
]

pretrain_weights: https://paddledet.bj.bcebos.com/models/yolov3_darknet53_270e_coco.pdparams
snapshot_epoch: 2
#weights: output/ppyolov2_r50vd_dcn_365e_mot_ch/model_final
metric: COCO
num_classes: 1

TrainDataset:
  !COCODataSet
    image_dir: ""  #train
    anno_path: annotations/train.json
    dataset_dir: dataset/mix_mot_ch #MOT
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/val_half.json
    dataset_dir: dataset/MOT

TestDataset:
  !ImageFolder
    anno_path: annotations/val_half.json

snapshot_epoch: 2
weights: output/mot_yolov3_darknet53_270e_coco/model_final

epoch: 90
LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 72
    - 81
  - !LinearWarmup
    start_factor: 0.
    steps: 400

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2