_BASE_: [
  './ppyoloe_crn.yml',
]

YOLOv3:
  backbone: ConvNeXt
  neck: CustomCSPPAN
  yolo_head: PPYOLOEHead
  post_process: ~

ConvNeXt:
  depths: [3, 3, 9, 3]
  dims: [96, 192, 384, 768]
  return_idx: [1, 2, 3]
  drop_path_rate: 0.4
  layer_scale_init_value: 1.0
  pretrained: https://paddledet.bj.bcebos.com/models/pretrained/convnext_tiny_1k_224_ema.pdparams
