_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov5p6_cspdarknet.yml',
  '_base_/yolov5p6_reader.yml',
]
snapshot_epoch: 5
weights: output/yolov5p6_n_coco/model_final

depth_factor: 0.33
width_factor: 0.25
