_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov5_cspdarknet.yml',
  '_base_/yolov5_reader.yml',
]

snapshot_epoch: 5
weights: output/yolov5_m_coco/model_final

depth_factor: 0.67
width_factor: 0.75

worker_num: 4
TrainReader:
  batch_size: 40
  use_shared_memory: true
