_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov5_cspdarknet.yml',
  '_base_/yolov5_reader.yml',
]
depth_factor: 1.33
width_factor: 1.25

log_iter: 100
snapshot_epoch: 10
weights: output/yolov5_x_coco/model_final
