_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov5p6_cspdarknet.yml',
  '_base_/yolov5p6_reader.yml',
]
weights: output/yolov5_p6_s_coco/model_final

depth_factor: 0.33
width_factor: 0.50

############   for debug  ############
TrainDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017_im4.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    #anno_path: annotations/instances_val2017_im8.json
    dataset_dir: dataset/coco

log_iter: 1 #20
snapshot_epoch: 10

worker_num: 0 # 2
TrainReader:
  inputs_def:
    num_max_boxes: 120
  sample_transforms:
    - Decode: {}
    - RGBReverse: {}
    - MosaicPerspective: {target_size: 1280} #  # x y w h
    - BboxPixelXYXY2NormCXCYWH: {}
    #- LetterBox: {target_size: 1280, auto: False, scaleup: False}
    #- Albumentations: {}
    - RandomHSV: {hgain: 0.015, sgain: 0.7, vgain: 0.4}
    - RandomFlip: {}
    - BboxXYXY2XYWH: {}
    - NormalizeBox: {}
    - NormalizeImage: {mean: [0, 0, 0], std: [1, 1, 1], is_scale: True}
    - RGBReverse: {}
    - Permute: {}
  batch_transforms:
    - Gt2Yolov5Target: 
        anchor_masks: [[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]]
        anchors: [[19, 27], [44, 40], [38, 94],
                  [96, 68], [86, 152], [180, 137],
                  [140, 301], [303, 264], [238, 542],
                  [436, 615], [739, 380], [925, 792]]
        downsample_ratios: [8, 16, 32, 64]
  batch_size: 4
  shuffle: False
  drop_last: True
  use_shared_memory: True
  collate_batch: True # False TODO
  mosaic_epoch: 300


EvalReader:
  sample_transforms:
    - Decode: {}
    - LetterBox: {target_size: 1280, auto: True, scaleup: True}
    - NormalizeImage: {mean: [0, 0, 0], std: [1, 1, 1], is_scale: True}
    - Permute: {}
  batch_size: 1


TestReader:
  inputs_def:
    image_shape: [3, 1280, 1280]
  sample_transforms:
    - Decode: {}
    - LetterBox: {target_size: [1280, 1280], auto: False, scaleup: False}
    - NormalizeImage: {mean: [0, 0, 0], std: [1, 1, 1], is_scale: True}
    - Permute: {}
  batch_size: 1


epoch: 10
LearningRate:
  base_lr: 0.01
  schedulers:
    - !OneCycle
      max_epochs: 10
      use_warmup: True
    - !ExpWarmup
      start_lr: 0.
      warmup_epochs: 3

OptimizerBuilder:
  optimizer:
    type: "Momentum"
    momentum: 0.937
    use_nesterov: True
    param_groups:
      - params: ['bias', 'bn']
        weight_decay: 0.0
  regularizer:
    factor: 0.0005
    type: L2
