_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov5_cspdarknet.yml',
  '_base_/yolov5_reader.yml',
]
weights: output/yolov5_s_coco/model_final

depth_factor: 0.33
width_factor: 0.50

epoch: 150
LearningRate:
  base_lr: 0.01
  schedulers:
    - !OneCycle
      max_epochs: 150
      use_warmup: True
    - !ExpWarmup
      start_lr: 0.
      warmup_epochs: 3

OptimizerBuilder:
  optimizer:
    type: "Momentum"
    momentum: 0.937
    use_nesterov: True
    param_groups:
      - params: ['bias', 'bn']
        weight_decay: 0.0
  regularizer:
    factor: 0.0005
    type: L2
